### ISSUE TITLE
no module named 'metaphor'

### ISSUE THREAD

**Issue by pyorz** [danielgibert/mlw_classification_hydra#1]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'. 
My email：catgray61@gmail.com

**Comment by CaptainZZL** [comment]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'.
My email：A1170814811@163.com

**Comment by DDmaker** [comment]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'.
My email：aykhuang@163.com

**Comment by haha744** [comment]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'.
My email：optimus_he@126.com

**Comment by rong0525** [comment]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'.
My email：yanglirong@bupt.edu.cn

**Comment by danielgibert** [comment]
You can use PE Parser to get the opcodes or the hex data as a list. 

https://github.com/danielgibert/pe_parser

**Comment by Yln12** [comment]
Hi, Daniel!
I've read your codes of Hydra, there is a module named 'metaphor' which is used to get_opcodes_data_as_list() and get_hexadecimal_data_as_list(). I am interested in your work and decide to run Hydra's code, I would really appreciate if you can offer me the source code of 'metaphor'.
My email：15054175521@163.com
